### PR TITLE
Build library for single, double and extended precison

### PR DESCRIPTION
**Pull request by kohr-h**
This will be needed for https://github.com/pyNFFT/pyNFFT/pull/63

---

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kohr-h** [comment]
@conda-forge-admin please rerender

**Comment by grlee77** [comment]
Looks good to me.

**Comment by grlee77** [comment]
I see the following warnings, but this should not be the fault of this PR. The same thing has occurred for other packages like VTK where various build-time paths get included in the pkgconfig files

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=32498&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=c09a5a47-eec3-5700-9284-6f1bd7b23501&lineStart=13290&lineEnd=13291&colStart=1&colEnd=1

**Comment by kohr-h** [comment]
Do you mean the "hardcoded path" warnings? I've seen those a lot, too. Not sure if something needs to be done, though.

**Comment by grlee77** [comment]
Yes. I think it is only a problem if some oneuses pkg-config. We can just ignore it for now

**Pull request merged**
